---

- name: Install dependencies on Debian based systems
  include_tasks: install_debian.yml
  when: "ansible_os_family == 'Debian' or ansible_distribution == 'Pengwin'"

- name: Install with Git
  include_tasks: install_with_git.yml
  when: not linuxbrew_use_installer

- name: Install using the installer script
  include_tasks: install_with_installer.yml
  when: linuxbrew_use_installer
